# Generated by Django 5.0.6 on 2024-08-05 07:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Users',
            new_name='Insaan',
        ),
    ]
